modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="magitech"
version="${file.jarVersion}"
displayName="Empirical Arcana"
logoFile="magitech.png"
credits="Credits go here"
authors="Authors go here"
description=''' '''
[[dependencies.space_mod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
